version: "3.8"

services:
    db:
        image: docker.pkg.github.com/farmacodeunipd/poc/db:latest
        build:
            context: ./db
            dockerfile: Dockerfile.db  
        ports:
            - "3306:3306"

    react-app:
        image: docker.pkg.github.com/farmacodeunipd/poc/react-app:latest
        build:
            context: ./client
            dockerfile: Dockerfile.client
        ports:
            - "3000:3000"
        depends_on:
            - db

    python-api:
        image: docker.pkg.github.com/farmacodeunipd/poc/python-api:latest
        build:
            context: ./algo
            dockerfile: Dockerfile.python
        ports:
            - "4000:4000"
        depends_on:
            - db

    express:
        image: docker.pkg.github.com/farmacodeunipd/poc/express:latest
        depends_on:
            - db
        build:
            context: ./express
            dockerfile: Dockerfile.express
        ports:
            - "3080:3080"
