version: "3.8"

services:
    db:
        image: mysql:latest
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            #- MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
            #- MYSQL_ALLOW_EMPTY_PASSWORD=ok
            - MYSQL_ROOT_HOST=localhost
            - MYSQL_HOST=*
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=mydatabase
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=mypassword
            - MYSQL_TCP_PORT=3306
        volumes:
            - "./db:/docker-entrypoint-initdb.d"
        expose:
            - 3306
        ports:
            - "3306:3306"

    react-app:
        build:
            context: ./client
            dockerfile: Dockerfile.client
        ports:
            - "3000:3000"

    python-api:
        build:
            context: ./algo
            dockerfile: Dockerfile.python
        ports:
            - "4000:4000"

    express:
        depends_on:
            - db
        build:
            context: ./express
            dockerfile: Dockerfile.express
        ports:
            - "5000:5000"

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin:latest

    #     environment:
    #         - PMA_HOST=db
    #         - PMA_PORT=3306
    #     ports:
    #         - "8080:80"

    # php-api:
    #     build:
    #         context: ./api
    #         dockerfile: Dockerfile.api
    #     ports:
    #         - "8082:80"
