# Use the official MySQL image as the base image
FROM mysql:latest

# Set the default authentication plugin for MySQL
CMD ["mysqld", "--default-authentication-plugin=mysql_native_password"]

# Set environment variables for MySQL configuration
ENV MYSQL_ROOT_HOST=localhost
ENV MYSQL_HOST=*
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword
ENV MYSQL_TCP_PORT=3306

# Install testing dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && pip3 install --no-cache-dir mysql-connector-python pytest

# Copy the SQL initialization script into the Docker image
COPY ./db.sql /docker-entrypoint-initdb.d/db.sql

# Expose MySQL port
EXPOSE 3306
