name: Run Tests

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d
          docker-compose ps
        # Adjust this step according to your project structure

      - name: Wait for services to start
        run: sleep 30s  # Adjust as needed

      - name: Run Tests
        run: |
          # Run your test commands here
          docker-compose exec react-app npm test
          docker-compose exec python-api pytest
          # Add more test commands for other services as needed

      - name: Tear down services
        run: docker-compose down