name: Run tests

on:
  push:
    branches:
      - main  # Esegui i test solo quando viene eseguito un push sulla branch main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t poc .

    - name: Run Docker container
      run: docker run poc

    - name: Run tests
      run: docker exec poc-python-api-1 pytest tests/test_algo.py

    - name: Stop and remove Docker containers
      run: docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)
