name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run MySQL tests
        run: |
          docker-compose run --rm db pytest /test/db.py

      - name: Run React App tests
        run: |
          docker-compose run --rm react-app npm test

      - name: Run Python API tests
        run: |
          docker-compose run --rm python-api pytest /test/algo.py

      - name: Run Express API tests
        run: |
          docker-compose run --rm express npm test
