name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mydatabase
          MYSQL_USER: myuser
          MYSQL_PASSWORD: mypassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 30s

      - name: Run Python API Tests
        run: |
          docker-compose exec python-api pytest /tests
          # Replace '/path/to/tests/directory' with the actual path to your tests directory within the container

      - name: Tear down services
        run: docker-compose down
