name: Docker Image Release

on:
  push:
    branches:
      - main

jobs:
  release-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fetch Tags
        run: git fetch --tags

      - name: Get Version
        run: |
          if [ -n "$(git tag --contains $GITHUB_SHA)" ]; then
            VERSION=$(git describe --tags --abbrev=0)
          else
            VERSION=$(git describe --always --abbrev=0)
          fi
          echo "Version: $VERSION"
          echo "::set-env name=VERSION::$VERSION"
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Tag Docker images
        run: docker tag poc docker.pkg.github.com/farmacodeunipd/poc/poc:$VERSION

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.PAT }}" | docker login docker.pkg.github.com -u farmacodeunipd --password-stdin

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: docker exec poc_python-api_1 pytest tests/test_algo.py
        continue-on-error: true

      - name: Check test status and push Docker images
        if: ${{ failure() != true }}
        run: |
          docker-compose build
          docker-compose push

      - name: Stop and remove Docker containers
        run: docker-compose down

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: $VERSION
          release_name: Release $VERSION
          body: |
            Release $VERSION

            - Rilascio versione $VERSION
