name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u farmacodeunipd --password-stdin

    - name: Build and push Docker images
      run: docker-compose build && docker-compose push

    - name: Set up Docker Compose
      run: docker-compose up -d

    - name: Run tests
      run: docker exec poc_python-api_1 pytest tests/test_algo.py

    - name: Stop and remove Docker containers
      run: docker-compose down
