name: Docker Image Release

on:
  push:
    branches:
      - main

jobs:
  release-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fetch Tags
        run: git fetch --tags

      - name: Get Version
        id: versioning
        run: |
          if [ -n "$(git tag --contains $GITHUB_SHA)" ]; then
            VERSION=$(git describe --tags --abbrev=0)
          else
            VERSION=$(git describe --always --abbrev=0)
          fi
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"
          
          # Increment version based on commit messages
          if git log --format=%B -n 1 $GITHUB_SHA | grep -q "version-major"; then
            VERSION=$(echo $VERSION | awk -F. '{$1++; print $0}')
          elif git log --format=%B -n 1 $GITHUB_SHA | grep -q "version-mid"; then
            VERSION=$(echo $VERSION | awk -F. '{$2++; print $0}')
          elif git log --format=%B -n 1 $GITHUB_SHA | grep -q "version-minor"; then
            VERSION=$(echo $VERSION | awk -F. '{$3++; print $0}')
          fi
          echo "Updated Version: $VERSION"
          echo "::set-output name=updated_version::$VERSION"
          
        env:
          GITHUB_SHA: ${{ github.sha }}

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.PAT }}" | docker login docker.pkg.github.com -u farmacodeunipd --password-stdin

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Run tests
        run: docker exec poc_python-api_1 pytest tests/test_algo.py
        continue-on-error: true

      - name: Check test status and push Docker images
        if: ${{ failure() != true }}
        run: |
          docker images
          docker rmi -f $(docker images -q)
          docker-compose build
          docker images
          IMAGES=("db" "python-api" "react-app" "express") # List of image names
          for IMAGE in "${IMAGES[@]}"; do
            # Tag e push con la versione aggiornata
            docker tag $IMAGE docker.pkg.github.com/farmacodeunipd/poc/$IMAGE:${{ steps.versioning.outputs.updated_version }}
            docker push docker.pkg.github.com/farmacodeunipd/poc/$IMAGE:${{ steps.versioning.outputs.updated_version }}
            
            # Tag e push con il tag "latest"
            docker tag $IMAGE docker.pkg.github.com/farmacodeunipd/poc/$IMAGE:latest
            docker push docker.pkg.github.com/farmacodeunipd/poc/$IMAGE:latest
          done

      - name: Stop and remove Docker containers
        run: docker-compose down

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.versioning.outputs.updated_version }}
          release_name: Release ${{ steps.versioning.outputs.updated_version }}
          body: |
            Release ${{ steps.versioning.outputs.updated_version }}
