name: Python and React/JS application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.5"

      - name: Install Python dependencies
        run: |
          pip install ruff

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install ESLint and dependencies
        run: |
          npm install eslint eslint-plugin-react eslint-config-react-app @babel/plugin-proposal-private-property-in-object --save-dev

      - name: Lint with Ruff (Python)
        run: |
          ruff check . --fix
          ruff format .

      - name: Lint with ESLint (React/JS)
        run: |
          npx eslint . --ext .js,.jsx --fix
